### ISSUE TITLE
Trouble setting up an environment that is neither 'mmm' nor 'yellowstone'

### ISSUE THREAD

**Issue by mgduda** [daniel-j-henderson/MPAS-Testing-Framework#3]
I'm trying to create a configuration file for 'kuusi', which uses libraries other than those in the
standard 'mmm' environment. When I execute a test that involves running a model executable
(in the output, below, the 'bit-reproducibility') test, I get the following:
```
>python ../MPAS-Testing-Framework/test_driver.py -env /sysdisk1/duda/regtesting/mgduda/MPAS-Testing-Framework/kuusi.xml -src /sysdisk1/duda/regtesting/MPAS-Release bit-reproducibility compile_gnu
Found netCDF module
Found numpy module
Max Cores: 12
'-env' is not a test module, skipping it
'/sysdisk1/duda/regtesting/mgduda/MPAS-Testing-Framework/kuusi.xml' is not a test module, skipping it
'-src' is not a test module, skipping it
'/sysdisk1/duda/regtesting/MPAS-Release' is not a test module, skipping it

Starting compile_gnu test.

real	5m35.470s
user	4m8.071s
sys	0m10.325s

Starting bit-reproducibility test.
Unknown environment.
file found: /sysdisk1/duda/regtesting/Standard-Library/meshes/40962/x1.40962.init.nc
Unknown environment.
file found: /sysdisk1/duda/regtesting/Standard-Library/meshes/40962/x1.40962.graph.info.part.4
Unknown environment.
file found: /sysdisk1/duda/regtesting/Standard-Library/meshes/40962/x1.40962.graph.info.part.8
/sysdisk1/duda/regtesting/mgduda/tests/regtest.2017-03-20_20.13.57/bit-reproducibility/nproc4
Process modelProcess-2:2:
Traceback (most recent call last):
  File "/sysdisk1/duda/Thursday_test/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/sysdisk1/duda/regtesting/mgduda/MPAS-Testing-Framework/utils/utils.py", line 159, in run
    res = self.main(self.args)
  File "/sysdisk1/duda/regtesting/mgduda/MPAS-Testing-Framework/utils/utils.py", line 348, in __runModelNonblocking__
    return runModel(args['dir'], args['exename'], args['n'], args['env'], args['add_lsfoptions'], args['add_pbsoptions'])
  File "/sysdisk1/duda/regtesting/mgduda/MPAS-Testing-Framework/utils/utils.py", line 379, in runModel
    err = os.system(cmd)
UnboundLocalError: local variable 'cmd' referenced before assignment
/sysdisk1/duda/regtesting/mgduda/tests/regtest.2017-03-20_20.13.57/bit-reproducibility/nproc8
Process modelProcess-2:4:
Traceback (most recent call last):
  File "/sysdisk1/duda/Thursday_test/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/sysdisk1/duda/regtesting/mgduda/MPAS-Testing-Framework/utils/utils.py", line 159, in run
    res = self.main(self.args)
  File "/sysdisk1/duda/regtesting/mgduda/MPAS-Testing-Framework/utils/utils.py", line 348, in __runModelNonblocking__
    return runModel(args['dir'], args['exename'], args['n'], args['env'], args['add_lsfoptions'], args['add_pbsoptions'])
  File "/sysdisk1/duda/regtesting/mgduda/MPAS-Testing-Framework/utils/utils.py", line 379, in runModel
    err = os.system(cmd)
UnboundLocalError: local variable 'cmd' referenced before assignment
Process bit-reproducibility:
Traceback (most recent call last):
  File "/sysdisk1/duda/Thursday_test/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "../MPAS-Testing-Framework/test_driver.py", line 67, in run
    self.myTest(self.tparams, self.result)
  File "/sysdisk1/duda/regtesting/mgduda/MPAS-Testing-Framework/bit-reproducibility/bit-reproducibility.py", line 80, in test
    res.set('err_code', e4.get('err_code')+e8.get('err_code'))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
Build / GNU test succeeded
   with error code 0
Test did not complete.
Bit-reproducibility test failed
Done.
```

I think the issue is related to this block of code in the `utils.py` module:
```
        if env.get('name') == 'yellowstone' or env.get('type') == Environment.ENVLSF:
                args = []
                lsf_options = env.get('lsf_options')
                lsf_options['-K'] = ''
                for key, value in lsf_options.items():
                        if key in add_lsfoptions:
                                continue
                        args.append(str(key) + ' ' + str(value))
                for key, value in add_lsfoptions.items():
                        args.append(str(key) + ' ' + str(value))

                cmd = 'bsub -n ' + str(n) + ' '
                for option in args:
                        cmd += option + ' '
                cmd += 'mpirun.lsf ./'+exename
                print(cmd)

        elif env.get('type') == Environment.ENVPBS:
                print('Running on '+env.get('name')+', a PBS system.')
                cmd = ''

        elif env.get('name') == 'mmm' or env.get('type') == Environment.NONE:
                cmd = 'mpirun -n '+str(n)+' ./'+exename
                print(cmd)
```
I'm not sure how to set the environment `type` to Environment.NONE, only how to set the environment `name`.

**Comment by daniel-j-henderson** [comment]
Oh ya I think I started out using the idea of 'type' then started using something else... New commit uses 'type' in xml files, utils module, and test_driver.py. Any reference to 'batchsystem' option should be replaced with 'type', see yellowstone.xml and cocobolo.xml
